# Generated by Django 2.2.5 on 2019-09-12 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='do_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('Important', '***'), ('Medium', '**'), ('small', '*')], default='small', max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('event_date', models.DateField(default=datetime.date(2019, 9, 12))),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
