# Generated by Django 2.2.5 on 2019-09-13 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='do_list',
            name='event_date',
            field=models.DateField(default=datetime.date(2019, 9, 13)),
        ),
        migrations.AlterField(
            model_name='do_list',
            name='item',
            field=models.CharField(default='None Item', max_length=100),
        ),
        migrations.AlterField(
            model_name='do_list',
            name='priority',
            field=models.CharField(choices=[('***', 'Important'), ('**', 'Medium'), ('*', 'small')], default='small', max_length=20),
        ),
    ]
