# Generated by Django 2.2.5 on 2019-09-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_auto_20190913_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='do_list',
            name='deleted',
        ),
        migrations.AlterField(
            model_name='do_list',
            name='priority',
            field=models.CharField(choices=[('Very important', '***'), ('Major', '**'), ('minor', '*')], default='minor', max_length=20),
        ),
    ]
