# Generated by Django 2.2.5 on 2019-09-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0003_auto_20190913_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='do_list',
            name='priority',
            field=models.CharField(choices=[('***', 'Very important'), ('**', 'Major'), ('*', 'minor')], default='*', max_length=20),
        ),
    ]
