# Generated by Django 2.2.5 on 2019-09-17 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0005_auto_20190916_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='do_list',
            name='event_date',
            field=models.DateField(default=datetime.date(2019, 9, 18)),
        ),
    ]
