# Generated by Django 2.2.5 on 2019-09-19 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0006_auto_20190918_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='do_list',
            name='event_date',
            field=models.DateField(default=datetime.date(2019, 9, 19)),
        ),
    ]
