# Generated by Django 2.2.5 on 2019-09-24 15:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0009_auto_20190924_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='do_list',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 24, 15, 11, 15, 277431, tzinfo=utc)),
        ),
    ]
