# Generated by Django 2.2.5 on 2019-09-24 15:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0013_auto_20190924_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='do_list',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 24, 15, 40, 56, 311323, tzinfo=utc)),
        ),
    ]
