# Generated by Django 2.2.5 on 2019-09-27 08:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0014_auto_20190924_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='do_list',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 27, 8, 57, 42, 998158, tzinfo=utc)),
        ),
    ]
