# Generated by Django 2.2.5 on 2019-09-28 19:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0022_auto_20190929_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='do_list',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 28, 19, 27, 55, 828769, tzinfo=utc)),
        ),
    ]
