# Generated by Django 2.2.5 on 2019-09-29 07:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0024_auto_20190929_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='do_list',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 29, 7, 32, 57, 666241, tzinfo=utc)),
        ),
    ]
