# Generated by Django 2.2.5 on 2019-09-30 15:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0029_auto_20190930_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='do_list',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 30, 15, 32, 14, 736366, tzinfo=utc)),
        ),
    ]
