# Generated by Django 2.2.5 on 2019-10-01 05:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0031_auto_20190930_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='do_list',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 1, 5, 55, 49, 947873, tzinfo=utc)),
        ),
    ]
