# Generated by Django 2.2.5 on 2019-09-28 18:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_auto_20190929_0106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bbs',
            options={'ordering': ('-post_date',)},
        ),
        migrations.AddField(
            model_name='bbs',
            name='post_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bbs',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 28, 18, 46, 57, 147976, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='bbs',
            name='post_hates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bbs',
            name='post_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bbs',
            name='post_title',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AddField(
            model_name='bbs',
            name='post_type',
            field=models.CharField(choices=[('分享', 'share'), ('心情', 'mood'), ('爆卦', 'gossip'), ('請益', 'question')], default='share', max_length=30),
        ),
        migrations.AlterField(
            model_name='bbs',
            name='postman',
            field=models.CharField(default='訪客', max_length=25),
        ),
        migrations.CreateModel(
            name='bbs_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=150)),
                ('comment_num', models.IntegerField(default=0)),
                ('comment_man', models.CharField(default='訪客', max_length=25)),
                ('comment_date', models.DateField(default=datetime.datetime(2019, 9, 28, 18, 46, 57, 148974, tzinfo=utc))),
                ('comment_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.bbs')),
            ],
            options={
                'db_table': 'bbs_comment',
                'ordering': ('-comment_date',),
            },
        ),
    ]
