# Generated by Django 2.2.5 on 2019-09-28 19:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0004_auto_20190929_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 28, 19, 16, 59, 864065, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bbs_comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 28, 19, 16, 59, 864065, tzinfo=utc)),
        ),
    ]
