# Generated by Django 2.2.5 on 2019-09-30 11:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0008_auto_20190929_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bbs_comment',
            name='comment_num',
        ),
        migrations.AlterField(
            model_name='bbs',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 30, 11, 1, 9, 551547, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bbs_comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 30, 11, 1, 9, 552545, tzinfo=utc)),
        ),
    ]
