# Generated by Django 2.2.5 on 2019-09-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='memeber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cName', models.CharField(max_length=20)),
                ('cSex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=5)),
                ('cBirthday', models.DateField()),
                ('cPhone', models.CharField(max_length=50)),
            ],
        ),
    ]
