# Generated by Django 2.2.5 on 2019-09-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='memeber',
            new_name='member',
        ),
    ]
