# Generated by Django 2.2.5 on 2019-09-04 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190904_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='cBirthday',
            new_name='Birthday',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='cName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='cPhone',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='cSex',
            new_name='Sex',
        ),
    ]
