# Generated by Django 2.2.5 on 2019-09-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190904_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
    ]
