# Generated by Django 2.2.5 on 2019-09-08 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190906_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Birthday',
            field=models.DateField(default=datetime.date(1990, 1, 20)),
        ),
        migrations.AlterField(
            model_name='member',
            name='Phone',
            field=models.CharField(default='09XXXXXXXX', max_length=50),
        ),
    ]
