# Generated by Django 2.2.5 on 2019-09-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190908_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Image', models.CharField(max_length=50)),
                ('intro', models.TextField()),
                ('href', models.CharField(max_length=80)),
            ],
        ),
    ]
