# Generated by Django 2.2.5 on 2019-09-19 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='create_date',
            field=models.DateField(default=datetime.date(2019, 9, 19)),
        ),
    ]
