# Generated by Django 2.2.5 on 2019-09-19 08:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_articles_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='href',
            new_name='Href',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='intro',
            new_name='Intro',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='create_date',
        ),
        migrations.AddField(
            model_name='articles',
            name='Create_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 19, 8, 33, 17, 417250, tzinfo=utc)),
        ),
    ]
