# Generated by Django 2.2.5 on 2019-09-19 12:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20190919_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='Create_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 19, 12, 55, 56, 290714, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visit_num',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
