# Generated by Django 2.2.5 on 2019-09-19 15:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20190919_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='Create_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 19, 15, 51, 26, 63714, tzinfo=utc)),
        ),
    ]
