# Generated by Django 2.2.5 on 2019-09-19 18:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20190920_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='Create_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 19, 18, 35, 37, 759919, tzinfo=utc)),
        ),
    ]
