# Generated by Django 2.2.5 on 2019-09-19 18:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20190920_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='Create_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 19, 18, 40, 43, 405220, tzinfo=utc)),
        ),
    ]
