# Generated by Django 2.2.5 on 2019-09-24 15:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20190924_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='Create_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 24, 15, 11, 15, 275436, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='Birthday',
            field=models.DateField(default=datetime.datetime(2019, 9, 24, 15, 11, 15, 275436, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='member',
            table='mem',
        ),
    ]
