# Generated by Django 2.2.5 on 2019-09-24 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20190924_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='Create_date',
            field=models.DateField(default=datetime.date(2019, 9, 24)),
        ),
        migrations.AlterField(
            model_name='member',
            name='Birthday',
            field=models.DateField(default=datetime.date(1990, 1, 20)),
        ),
    ]
