# Generated by Django 2.2.5 on 2019-09-24 15:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20190924_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='Create_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 24, 15, 30, 10, 189060, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='articles',
            table=None,
        ),
        migrations.AlterModelTable(
            name='member',
            table=None,
        ),
        migrations.AlterModelTable(
            name='visit_num',
            table=None,
        ),
    ]
