# Generated by Django 2.2.5 on 2019-09-24 15:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20190924_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='Create_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 24, 15, 36, 59, 330, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='articles',
            table='articles',
        ),
        migrations.AlterModelTable(
            name='member',
            table='mem',
        ),
        migrations.AlterModelTable(
            name='visit_num',
            table='visit_num',
        ),
    ]
