# Generated by Django 2.2.5 on 2019-09-28 15:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20190927_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='Create_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 28, 15, 30, 4, 887558, tzinfo=utc)),
        ),
    ]
