# Generated by Django 2.2.5 on 2019-09-28 16:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20190929_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='Create_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 28, 16, 39, 1, 756249, tzinfo=utc)),
        ),
    ]
