# Generated by Django 2.2.5 on 2019-09-29 06:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_auto_20190929_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='Create_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 29, 6, 4, 49, 21605, tzinfo=utc)),
        ),
    ]
